# Generated by Django 6.0.5 on 2026-05-16 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
