# Generated by Django 6.0.5 on 2026-05-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.IntegerField(default=0)),
                ('short_url', models.URLField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('agent', models.TextField(blank=True, null=True)),
                ('refer', models.URLField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
