# Generated by Django 6.0.5 on 2026-05-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_clickanalytics_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickanalytics',
            name='user',
        ),
    ]
