# Generated by Django 6.0.5 on 2026-05-17 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_clickanalytics_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickanalytics',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='clickanalytics',
            name='click',
        ),
        migrations.AddField(
            model_name='clickanalytics',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clickanalytics',
            name='short_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='task.urldata'),
        ),
    ]
