# Generated by Django 6.0.5 on 2026-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_clickanalytics_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='total_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
