# Generated by Django 6.0.5 on 2026-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_urldata_total_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
